<a href="https://colab.research.google.com/github/CuiyingLin17/IS477BusinessCoders/blob/main/acquire_DSPI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import os
import requests
import hashlib

In [4]:
os.makedirs("data/raw", exist_ok=True)

DSPI_url = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=DSPI&scale=left&cosd=1959-01-01&coed=2026-01-01&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Monthly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-04-05&revision_date=2026-04-05&nd=1959-01-01"
DSPI_filename = "DSPI.csv"

response = requests.get(DSPI_url)

with open(DSPI_filename, "wb") as f:
    f.write(response.content)

print("Saved DSPI dataset:", DSPI_filename)

Saved DSPI dataset: DSPI.csv

In [5]:
def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()

print("DSPI SHA-256:", sha256(DSPI_filename))

DSPI SHA-256: 4625d32471de851b08cc93a1740dfb51718507bb99c1ce80a0b1e8429ed42ad2

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv(DSPI_filename)
df.head()

  observation_date   DSPI
0       1959-01-01  351.5
1       1959-02-01  352.9
2       1959-03-01  355.2
3       1959-04-01  358.2
4       1959-05-01  360.3

In [8]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nData types:")
print(df.dtypes)

Shape: (805, 2)
Columns: ['observation_date', 'DSPI']

Data types:
observation_date     object
DSPI                float64
dtype: object

In [9]:
print("Missing values:")
print(df.isna().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Missing values:
observation_date    0
DSPI                0
dtype: int64

Duplicate rows: 0

In [10]:
df[df.columns[0]] = pd.to_datetime(df[df.columns[0]], errors="coerce")
df = df[(df["observation_date"] >= '2015-01-01') & (df["observation_date"] <= '2026-01-01')]
print("Date range:", df[df.columns[0]].min(), "to", df[df.columns[0]].max())

Date range: 2015-01-01 00:00:00 to 2026-01-01 00:00:00

In [11]:
df.head()

    observation_date     DSPI
672       2015-01-01  13335.7
673       2015-02-01  13408.1
674       2015-03-01  13397.8
675       2015-04-01  13439.5
676       2015-05-01  13494.8